### ISSUE TITLE
gst-transcoder is built with insecure RPATH

### ISSUE THREAD

**Issue by pacho2** [pitivi/gst-transcoder#3] opened 2016-07-31 09:17 UTC
I don't know if this is due to ninja or meson, but building gst-transcoder ends up using runtime paths:
-   /var/tmp/portage/media-plugins/gst-transcoder-1.8.1/image/usr/bin/gst-transcoder-1.0
-     RPATH: /var/tmp/portage/media-plugins/gst-transcoder-1.8.1/work/gst-transcoder-1.8.1/build/
-   /var/tmp/portage/media-plugins/gst-transcoder-1.8.1/image/usr/lib/libgsttranscoder-1.0.so.0
-     RPATH: /var/tmp/portage/media-plugins/gst-transcoder-1.8.1/work/gst-transcoder-1.8.1/build/
-   /var/tmp/portage/media-plugins/gst-transcoder-1.8.1/image/usr/lib/gstreamer-1.0/libgsttranscoderplugin.so
-     RPATH: /var/tmp/portage/media-plugins/gst-transcoder-1.8.1/work/gst-transcoder-1.8.1/build/

This should be avoided as explained in:
https://wiki.debian.org/RpathIssue

but I don't see how to avoid them with this build system

Thanks

**Comment by thiblahute** [comment] 2016-07-31 21:46
How did you install those files? Files installed by meson/ninja should not use rpath (I checked on my system and they indeed are not).

**Comment by pacho2** [comment] 2016-08-01 19:28
We simply run:
./configure --prefix=/usr
make
make install 

In our Gentoo ebuild :/

**Comment by thiblahute** [comment] 2016-08-01 19:31
And what version of meson do you have?

**Comment by pacho2** [comment] 2016-08-01 19:35
I have 0.33.0

**Comment by thiblahute** [comment] 2016-08-01 19:38
OK, then this is very weird, I can;t reproduce here.

**Comment by pacho2** [comment] 2016-08-01 19:46
How do you check for RPATHs? In Gentoo portage warns us about that... but maybe it's that causing the problem :/

Also, our ninja is 1.6.0

**Comment by thiblahute** [comment] 2016-08-01 19:58
I checked doing:

```
$ readelf -d mesonbuild/subprojects/gst-transcoder/libgsttranscoder-1.0.so|grep RPATH
 0x000000000000000f (RPATH)              Library rpath: [/home/thiblahute/devel/pitivi/flatpak/pitivi/mesonbuild/subprojects/gst-transcoder]
$ readelf -d /app/lib/libgsttranscoder-1.0.so|grep RPATH
$
```

ninja 1.6.0 should be good enough.

Could you share all the logs in `build/` and outputed in the terminal?

**Comment by jpakkane** [comment] 2016-08-01 20:00
I'm the developer of Meson and this should not be happening, those RPATHs are only used in the build tree, they are reset upon install.

Please run these steps manually for gst-transcoder:

```
mkdir builddir
cd builddir
meson ..
DESTDIR=/tmp/foo ninja install
```

The shared libs should be in /tmp/foo/usr/local/lib<something>. You can get them by doing 

```
python3 /path/to/meson/mesonbuild/scripts/depfixer.py <path to lib>
```

If they are still there, run this command (note the quotes at the end):

```
 python3 /path/to/meson/mesonbuild/scripts/depfixer.py <path to lib> ''
```

Then run the previous command again. Have they gone away now?

**Comment by pacho2** [comment] 2016-08-01 20:31
If I build it with ./configure && make && make install ... it installs the libs with RPATH, but if I build them as you (under buildir), it works ok and the files in /tmp/foo are RPATH free :/

**Comment by jpakkane** [comment] 2016-08-01 20:37
What if you set your ebuild commands to do the following:

```
mkdir builddir
meson builddir --prefix=/usr
ninja -C builddir -v
DESTDIR=[whatever value] ninja -C builddir install
```

Note the `-v`, it is mandatory at least on Debian to show compiler invocations in the log file so quality checkers can verify that all the necessary hardening flags are being used.

You might want to add `--buildtype=plain` if Gentoo injects compiler flags to use via `CFLAGS` etc and `--buildtype=debugoptimized` if it does not.

**Comment by pacho2** [comment] 2016-08-01 21:34
If I manually run that commands... it starts to install the files with RPATH again:
$ meson builddir --prefix=/usr
The Meson build system
Version: 0.33.0
Source dir: /home/pacho/Descargas/gst-transcoder-1.8.1
Build dir: /home/pacho/Descargas/gst-transcoder-1.8.1/builddir
Build type: native build
Build machine cpu family: x86_64
Build machine cpu: x86_64
Project name: gst-renderer
Native c compiler: ccache cc (gcc 4.9.3)
Checking for function "getrusage": YES
Found pkg-config: /usr/bin/pkg-config (0.29.1)
Native dependency gobject-2.0 found: YES 2.48.1
Native dependency glib-2.0 found: YES 2.48.1
Native dependency gstreamer-1.0 found: YES 1.8.2
Native dependency gstreamer-pbutils-1.0 found: YES 1.8.2
Build targets in project: 5
 $ ninja -C builddir -v
ninja: Entering directory `builddir'
[1/11] ccache cc  '-Igsttranscoder-1.0@sha' '-fdiagnostics-color=always' '-I..' '-I.' '-pipe' '-Wall' '-Winvalid-pch' '-Wno-pedantic' '-O0' '-g' '-fPIC' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-MMD' '-MQ' 'gsttranscoder-1.0@sha/gst-libs_gst_transcoding_transcoder_gsttranscoder.c.o' '-MF' 'gsttranscoder-1.0@sha/gst-libs_gst_transcoding_transcoder_gsttranscoder.c.o.d' -o 'gsttranscoder-1.0@sha/gst-libs_gst_transcoding_transcoder_gsttranscoder.c.o' -c ../gst-libs/gst/transcoding/transcoder/gsttranscoder.c
[2/11] ccache cc  '-Igst-transcoder-1.0@exe' '-fdiagnostics-color=always' '-I..' '-I.' '-pipe' '-Wall' '-Winvalid-pch' '-O0' '-g' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-MMD' '-MQ' 'gst-transcoder-1.0@exe/tools_gst-transcoder.c.o' '-MF' 'gst-transcoder-1.0@exe/tools_gst-transcoder.c.o.d' -o 'gst-transcoder-1.0@exe/tools_gst-transcoder.c.o' -c ../tools/gst-transcoder.c
[3/11] ccache cc  '-Igsttranscoderplugin@sha' '-fdiagnostics-color=always' '-I..' '-I.' '-pipe' '-Wall' '-Winvalid-pch' '-DHAVE_CONFIG_H' '-D_GNU_SOURCE' '-DGST_EXPORTS' '-DGST_DISABLE_DEPRECATED' '-O0' '-g' '-fPIC' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-MMD' '-MQ' 'gsttranscoderplugin@sha/gst_transcode_gsttranscodebin.c.o' '-MF' 'gsttranscoderplugin@sha/gst_transcode_gsttranscodebin.c.o.d' -o 'gsttranscoderplugin@sha/gst_transcode_gsttranscodebin.c.o' -c ../gst/transcode/gsttranscodebin.c
[4/11] ccache cc  '-Igsttranscoderplugin@sha' '-fdiagnostics-color=always' '-I..' '-I.' '-pipe' '-Wall' '-Winvalid-pch' '-DHAVE_CONFIG_H' '-D_GNU_SOURCE' '-DGST_EXPORTS' '-DGST_DISABLE_DEPRECATED' '-O0' '-g' '-fPIC' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-MMD' '-MQ' 'gsttranscoderplugin@sha/gst_transcode_gst-cpu-throttling-clock.c.o' '-MF' 'gsttranscoderplugin@sha/gst_transcode_gst-cpu-throttling-clock.c.o.d' -o 'gsttranscoderplugin@sha/gst_transcode_gst-cpu-throttling-clock.c.o' -c ../gst/transcode/gst-cpu-throttling-clock.c
[5/11] ccache cc  '-Igsttranscoderplugin@sha' '-fdiagnostics-color=always' '-I..' '-I.' '-pipe' '-Wall' '-Winvalid-pch' '-DHAVE_CONFIG_H' '-D_GNU_SOURCE' '-DGST_EXPORTS' '-DGST_DISABLE_DEPRECATED' '-O0' '-g' '-fPIC' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-pthread' '-I/usr/include/gstreamer-1.0' '-I/usr/lib64/gstreamer-1.0/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '-MMD' '-MQ' 'gsttranscoderplugin@sha/gst_transcode_gsturitranscodebin.c.o' '-MF' 'gsttranscoderplugin@sha/gst_transcode_gsturitranscodebin.c.o.d' -o 'gsttranscoderplugin@sha/gst_transcode_gsturitranscodebin.c.o' -c ../gst/transcode/gsturitranscodebin.c
[6/11] ccache cc    -o libgsttranscoder-1.0.so.0 'gsttranscoder-1.0@sha/gst-libs_gst_transcoding_transcoder_gsttranscoder.c.o' '-Wl,--no-undefined' '-shared' '-fPIC' '-Wl,-soname,libgsttranscoder-1.0.so.0' '-lglib-2.0' '-lgobject-2.0' '-lglib-2.0' '-lgstreamer-1.0' '-lgobject-2.0' '-lglib-2.0' '-lgstpbutils-1.0' '-lgstreamer-1.0' '-lgobject-2.0' '-lglib-2.0' '-Wl,-rpath,/home/pacho/Descargas/gst-transcoder-1.8.1/builddir/' 
[7/11] "/usr/bin/python3.5" "/usr/lib/python-exec/python3.5/meson.py" --internal symbolextractor libgsttranscoder-1.0.so.0 'gsttranscoder-1.0@sha/libgsttranscoder-1.0.so.0.symbols' 
[8/11] 'g-ir-scanner' '../gst-libs/gst/transcoding/transcoder/gsttranscoder.h' '../gst-libs/gst/transcoding/transcoder/gsttranscoder.c' '-pthread' '-I/usr/include/gobject-introspection-1.0' '-I/usr/lib64/libffi-3.2.1/include' '-I/usr/include/glib-2.0' '-I/usr/lib64/glib-2.0/include' '--no-libtool' '--namespace=GstTranscoder' '--nsversion=1.0' '--warn-all' '--output' 'GstTranscoder-1.0.gir' '--add-init-section=extern gboolean gst_init(gint *argc, gchar **argv); gst_init(NULL,NULL);' '--include=GObject-2.0' '--include=Gst-1.0' '--include=GstPbutils-1.0' '--symbol-prefix=gst_' '--identifier-prefix=Gst' '--add-include-path=/usr/share/gir-1.0' '-lgstreamer-1.0' '-lgobject-2.0' '-lglib-2.0' '-L/home/pacho/Descargas/gst-transcoder-1.8.1/builddir/.' '--library' 'gsttranscoder-1.0'
[9/11] ccache cc    -o libgsttranscoderplugin.so 'gsttranscoderplugin@sha/gst_transcode_gsttranscodebin.c.o' 'gsttranscoderplugin@sha/gst_transcode_gst-cpu-throttling-clock.c.o' 'gsttranscoderplugin@sha/gst_transcode_gsturitranscodebin.c.o' '-Wl,--no-undefined' '-shared' '-fPIC' '-Wl,-soname,libgsttranscoderplugin.so' '-lglib-2.0' '-lgobject-2.0' '-lglib-2.0' '-lgstreamer-1.0' '-lgobject-2.0' '-lglib-2.0' '-lgstpbutils-1.0' '-lgstreamer-1.0' '-lgobject-2.0' '-lglib-2.0' '-Wl,-rpath,/home/pacho/Descargas/gst-transcoder-1.8.1/builddir/' 
[10/11] ccache cc    -o gst-transcoder-1.0 'gst-transcoder-1.0@exe/tools_gst-transcoder.c.o' '-Wl,--no-undefined' 'libgsttranscoder-1.0.so.0' '-lglib-2.0' '-lgobject-2.0' '-lglib-2.0' '-lgstreamer-1.0' '-lgobject-2.0' '-lglib-2.0' '-lgstpbutils-1.0' '-lgstreamer-1.0' '-lgobject-2.0' '-lglib-2.0' '-Wl,-rpath,/home/pacho/Descargas/gst-transcoder-1.8.1/builddir/' 
[11/11] 'g-ir-compiler' 'GstTranscoder-1.0.gir' '--output' 'GstTranscoder-1.0.typelib' '--includedir=/usr/share/gir-1.0'
$ DESTDIR=/tmp/foo ninja -C builddir install
ninja: Entering directory`builddir'
[1/1] Installing files.
Installing gst-transcoder-1.0 to /tmp/foo/usr/bin/gst-transcoder-1.0
Installing GstTranscoder-1.0.typelib to /tmp/foo/usr/lib/girepository-1.0/GstTranscoder-1.0.typelib
Installing libgsttranscoder-1.0.so.0 to /tmp/foo/usr/lib64/libgsttranscoder-1.0.so.0
Installing GstTranscoder-1.0.gir to /tmp/foo/usr/share/gir-1.0/GstTranscoder-1.0.gir
Installing libgsttranscoderplugin.so to /tmp/foo/usr/lib64/gstreamer-1.0/libgsttranscoderplugin.so
Installing gsttranscoder.h to /tmp/foo/usr/include/gstreamer-1.0/gst/transcoder
Installing /home/pacho/Descargas/gst-transcoder-1.8.1/builddir/meson-private/gst-transcoder-1.0.pc to /tmp/foo/usr/lib64/pkgconfig.
$ readelf -d /tmp/foo/usr/lib64/libgsttranscoder-1.0.so|grep PATH
 0x000000000000001d (RUNPATH)            Ruta de ejecución de la biblioteca: [/home/pacho/Descargas/gst-transcoder-1.8.1/builddir/]

But the fixer thinks it's ok:
$ python3 /usr/lib64/python3.4/site-packages/mesonbuild/scripts/depfixer.py /tmp/foo/usr/lib64/libgsttranscoder-1.0.so
This file does not have an rpath.

**Comment by jpakkane** [comment] 2016-08-01 21:37
RUNPATH and RPATH are different settings.

**Comment by jpakkane** [comment] 2016-08-02 18:46
Can you try this branch and tell if it fixes the issue: https://github.com/mesonbuild/meson/pull/663

**Comment by pacho2** [comment] 2016-08-04 18:12
It works nice, thanks a lot :D

**Comment by pacho2** [comment] 2016-08-04 18:20
As a side note... if meson it meant to replace autotools in a near "transparent" way (I mean, providing ./configure && make && make install), wouldn't it be better to append --buildtype=plain by default? I mean, most autotools based packages will default to honoring the set CFLAGS/CXXFLAGS by default.

Also, maybe a --disable-silent-rules could be handled in ./configure to mimic autotools option and, that way, allow us to simply run "make" instead of manually calling ninja with the right options

Thanks

**Comment by jpakkane** [comment] 2016-08-04 18:35
Meson does not aim to replace Autotools transparently.  It does not have a Make backend and never will so having people call `make` to compile it is kinda pointless. Explicit is better than implicit (e.g. "magic"), having the commands out explicitly is less clutter.

**Comment by nirbheek** [comment] 2016-08-04 18:46
Also, Meson already defaults to honoring the `CFLAGS`/`CXXFLAGS` set in the environment.

**Comment by thiblahute** [comment] 2016-08-04 18:48
Yeah, I added the configure file myself to respect the [build API](https://github.com/cgwalters/build-api) making it simpler to build the project in flatpak. But it is really only my choice.

**Comment by pacho2** [comment] 2016-08-04 19:18
Ah, nice, it will be really useful for packaging it properly :)

Anyway I will still need to specify --buildtype=plain right? Because it seems "debug" is the default (at least that is what ./configure --help says)

**Comment by jpakkane** [comment] 2016-08-04 19:29
Yes. Though the configure/makefile thingy should probably do that (or `debugoptimized` to mimic Autotools behaviour) for you because it is for distro consumption.

**Comment by thiblahute** [comment] 2016-08-04 19:40
I prefer to have debug build by default and let packager pass the proper args tbh.

**Comment by thiblahute** [comment] 2018-02-21 13:04
Closing

**Closed as completed by thiblahute** 2018-02-21 13:04 UTC
